default_locale: en
hot_export:
  login_url: http://export.hotosm.org/users/sign_in
  logout_url: http://export.hotosm.org/users/sign_out
  upload_url: http://export.hotosm.org/uploads/new
  after_upload_url: http://export.hotosm.org/uploads/presets
