development:
    adapter: postgresql
    database: visualtags_development
    username: <%= ENV['PG_USER'] %>
    password: <%= ENV['PG_PASS'] %>
    host: localhost
    
test:
    adapter: postgresql
    database: visualtags_test
    username: <%= ENV['PG_USER'] %>
    password: <%= ENV['PG_PASS'] %>
    host: localhost
