development:
  adapter: postgresql
  database: visualtags_development
  username: <%= ENV['PG_USER'] %>
  password: <%= ENV['PG_PASS'] %>
  host: localhost
production:
    adapter: sqlite3
    database: visualtags.sqlite3.db
